### ISSUE TITLE
Cannot enable addon after installation, No module named BVtkNodes-0

### ISSUE THREAD

**Issue by rich4rdmacwan** [tkeskita/BVtkNodes#109]
Traceback: "/opt/blender-3.6.3-linux-x64/3.6/scripts/modules/addon_utils.py", line 333, in enable
mod = __import__(module_name)
ModuleNotFoundError: No module named 'BVtkNodes-0'

**Comment by tkeskita** [comment]
Please always download the latest master version of BVTKNodes from Github (Code --> Download ZIP). The tag "0.7" version is a bit old. I should not have even made that git tag because people accidentally download that. So I suggest you remove the old version and install the master one. Sorry for the inconvenience.

**Comment by rich4rdmacwan** [comment]
Got it, thank you for your reply.
