### ISSUE TITLE
Preprocessing and cutting planes in 3D data block

### ISSUE THREAD

**Issue by zloysmiertniy** [tkeskita/BVtkNodes#26]
Hello. I was in the Blender artists post and they say to ask questions here so, here it goes:

I managed to make the example in the introduction of the documentation and now I am excited to start with my own data. I know my way around Blender, even in Paraview. I learned to use VTK and ITK long ago but not a lot, only for some specific tasks. 

So my question is, can you recommend a good tutorial for converting the data to VTK so I can import it in Blender in BVTK? I have simply a block of 3D data, XYZ coordinates with 2 values associated to them. I was using a vtkPolyData is that a good one? and also, how would I go about taking several cuts of this block? I basically want to observe a few planes within my data along a specific path.

If I manage to create a vtk file with my data, which BVTK reader node should I add to read it?

I found this [cutting-field-data](https://bvtknodes.readthedocs.io/en/latest/ug_nodes.html#cutting-field-data), so maybe that answers part of my question but in this case I have to use a vtkPlane to cut the data but I was wondering if there is a way to connect a Blender plane instead, so I could almost dynamically move the plane in Blender but get the cut computed by VTK.

**Comment by tkeskita** [comment]
Hi,

I'd suggest first try to do it in Paraview (at least to read the data and see it's type and field names etc.), and then move on to BVTKNodes.

First thing is to identify which kind of data you have: https://lorensen.github.io/VTKExamples/site/VTKFileFormats/#dataset-format

It sounds like you have structured points with scalar data, maybe? In that case you can maybe convert your data to e.g. the legacy vtk file format described in that link, check that Paraview can read it OK, and then use **vtkStructuredPointsReader** to read in in BVTKNodes. Or if you already have it as *vtkPolyData* that I think is OK for arbitrary located point data, then use **vtkPolyDataReader** to read that in and process further. Which reader is correct depends on your data file format and data type.

For cutting (or sampling with a surface) you need to have the surface in VTK in order to do sampling on it. Conversion is currently one-way from VTK to Blender, so nothing done in Blender goes back to VTK. Another sampling example is in [volumetric example](https://bvtknodes.readthedocs.io/en/latest/ug_nodes.html#volumetric-rendering). If you want to sample on an arbitrary surface mesh, I think you could create mesh in Blender, read that in BVTKNodes and use that in sampling, but that is a bit cumbersome. Usually people need some specific isosurface etc. to sample on, that you can create with **vtkContourFilter**.

HTH,
Tuomo

**Comment by zloysmiertniy** [comment]
Thank you!!

I will check the link, looks useful. Yes I tried in paraview and there I can do some things.

So, lets put it this way: 

I have earthquake data that has an X,Y and Z. To each of those points there is a time data associated and a strength and a depth (that is actually just a copy of the Z coordinate)

Right now I handle them like this:

```
df=pd.read_csv(file,sep=sep)

#data processing here

points=df[['Latitude', 'Longitude', 'Depth']].to_numpy()
times=df["Time"].to_numpy()
scalars=df["Magnitude"].to_numpy()
depth=df["Depth"].to_numpy()

p = vtk.vtkPoints()
for i in range(points.shape[0]):
    p.InsertNextPoint(points[i,:])
s = numpy_support.numpy_to_vtk(scalars)
t = numpy_support.numpy_to_vtk(times)
d = numpy_support.numpy_to_vtk(depth)

points, scalars, tid, depth = p,s,t,d

scalars.SetName("magnitude")
tid.SetName("time")
depth.SetName("depth")
data = vtk.vtkPolyData()
data.SetPoints(points)
data.GetPointData().AddArray(scalars)
data.GetPointData().AddArray(tid)
data.GetPointData().AddArray(depth)
data.GetPointData().SetActiveScalars("magnitude")

# Write data to VTK legacy format that Paraview can import
writer = vtk.vtkPolyDataWriter()
writer.SetFileName("earthquake.vtk")
writer.SetFileTypeToBinary()
writer.SetInputData(data)
writer.Write()

```

When I load this in Paraview I can do things like this in this image: [earthquake](https://raw.githubusercontent.com/vetvis-uu/project/master/images/screenshot_earthquake_small.png)

And I want to be able to do something like this image that is block of data and has a plane that cuts and shows the values that lie on that plane [image](https://raw.githubusercontent.com/vetvis-uu/assignment1/master/part3/images/screenshot.png)

For now I don't need volumetric and I don't need iso contours. Just a cutting plane, To only show the data that is in that plane.

As for the communication between Blender structures and VTK I was wondering, since the example of [cutting field data](https://bvtknodes.readthedocs.io/en/latest/ug_nodes.html#cutting-field-data) needs a VTK plane and I don't know how to compute the normal the origin and the size, at least relative to the data or the view, so it could be cool to be able to have a way to target a plane in Blender and convert it to a VTKplane to connect to the rest of the BVTK nodes.

But it's a good start so far, thank you for your response!

**Comment by tkeskita** [comment]
Hi,

Thanks for clarifying code example! So you have unstructured point data to begin with. You need to create 3D cells from point data before you can slice them. Simplest is maybe e.g. instance a 3D glyph (sphere?) at those points (see [vector glyphs example](https://bvtknodes.readthedocs.io/en/latest/ug_nodes.html#vector-glyphs))? If you want a continuous rectangle for the slice then you need to create e.g. **VTKImageData Object Source** or maybe *vtkStructuredGrid* and sample your data to that somehow, then slice. That might be easier to do separately in Paraview.

Idea of using an object (maybe an Empty?) in Blender for positioning a vtkPlane is interesting, since planes are so often needed. I'll put that on my todo list to try it, shouldn't be too large thing to do!

BR,
Tuomo

**Comment by zloysmiertniy** [comment]
Thank you! ok I realize now that I have to change it to ImageData but there is no reader in BVTK for VTKImageData only XMLImageData. Can you tell me how can I convert it? or how to write it as XML Image Data? I was looking for examples [here](https://vtk.org/Wiki/VTK/Examples/Python) in the documentation but some links are broken.

Can I export it with Paraview? if so, how?

**Comment by zloysmiertniy** [comment]
BTW, if anyone else wonders, I was looking at the vtkPlane node and it has a link button! :D but it doesn't have and "unlink" but anyways, I can select a plane to cut the image! So cool.

Also, found PyEVTK https://vtk.org/Wiki/VTK/Writing_VTK_files_using_python#EVTK
EVTK = Export VTK so I managed to create a random image but I will have to find how to put my data into that. 

I think for now I will close this so you have a nicely closed issue. Thank you for all your answers.

We want to teach scientific data visualization with VTK so this is a huge step towards that. See you in a next question.

**Comment by tkeskita** [comment]
Hi,

ok I'll take a look at the link button in *vtkPlane* node, didn't realize such a thing was already there!

Resampling from unstructured point data I've never done, there must be some kind of point distance function resampling filter to do it, I only have [this sampling example from unstructured grids to vtkImageData](https://bvtknodes.readthedocs.io/en/latest/ug_nodes.html#volumetric-rendering).

Thanks for pyEVTK pointer, looks useful!

**Comment by tkeskita** [comment]
FYI: Object linking for vtkPlane was broken, now fixed in latest commit.

**Comment by tkeskita** [comment]
FYI: I had a little time, so I tried to use *vtkImplicitModeller* to map points to image data, but that didn't work well. Maybe something like *vtkPointInterpolator* could work? https://lorensen.github.io/VTKExamples/site/Python/Meshes/PointInterpolator/
Anyways, if you find a good point-to-imagedata interpolation solution please let me know, thanks! It sounds like a fairly common use case, so I could add an example to docs.
