### ISSUE TITLE
Color Mapper node color by vector field magnitude

### ISSUE THREAD

**Issue by renehommel** [tkeskita/BVtkNodes#58]
I do not know if the following problem has already been discussed: When using vtkStreamTracer, the velocity magnitude is not correctly mapped to the streamlines, as can be seen from the screenshot (right image). A coloring with the components u, v, or w works without problems (left image). I tried it with completely different datasets, always with the same result. Also changing the node settings does not solve the problem. What can be the reason?

I can share the VTU file, but it is about 50MB. 

<img width="1500" alt="streamlines_U" src="https://user-images.githubusercontent.com/31559173/115057996-05fb8080-9ee5-11eb-9451-ca63753988f5.png">

**Comment by tkeskita** [comment]
Hi @renehommel,

this is a very common problem. We should modify Color Mapper to improve this, so please let this issue remain open until a fix is applied. The reason is, your ResultArrayVector is a vector and Color Mapper needs a scalar. I think the Color Mapper should be modified so that if it encounters vector or tensor field it calculates magnitude and uses that. Current workaround is that somewhere upstream you must [calculate mag(x)](https://bvtknodes.readthedocs.io/en/latest/ug_nodes.html#field-data-calculations) and use it in Color Mapper.

**Comment by renehommel** [comment]
thanks for the clarification and the hint
