### ISSUE TITLE
ImportError: DLL load failed while importing vtkCommonCore

### ISSUE THREAD

**Issue by m3dus444** [tkeskita/BVtkNodes#91]
Hi, i have this issue when i try to import the module **after installing it with pip**. I'm working on **Windows 10 latest version**. 
Here's what's happening : 

![image](https://user-images.githubusercontent.com/79890844/193056080-5f9b46aa-8b46-4dc8-859f-c97318d84480.png)

As you see, I tried first the installations commands from _https://github.com/tkeskita/BVtkNodes/blob/master/pip_install_vtk.md_

Then, as pip told me i had to choose between two canditates (1 o 2), i've tried both same issue. 

When i try to import it from a python script or directly from command line as you see above, i have a dll import error.

If anyone knows how to fix that, it'd be great ❤️ . Thanks.

**Comment by tkeskita** [comment]
Hi,

you seem to be using Blender 3.3. BVTKNodes has not been upgraded to support Blender 3.3, 2.93 is the latest supported version. Since 3.3 is the latest LTS, I will try to find time next year to do the upgrade, but it's a big job.

BR,
Tuomo

**Comment by m3dus444** [comment]
Oh okay i see, i didn't checked the versions compatibility it's completely my bad. I understand it must be hard work to do, i'll down grade Blender that's totally fine.
Thank you and what to say, amazing job here with this module ! 😄

**Comment by dwerner95** [comment]
Hey, 

just as a note, i am running BVTKNodes in Blender 3.1 without issues (Ubuntu 20.04)
And i just installed it on Blender 3.3 without (unknown) issues.

In fact, i know what issue you have here.
For some reason the blender folder installed on windows is read only by default. Therefore modules installed with pip, (even with the blender version) will be installed in a different location.  ( The image you show even tells you : "Defaulting to user installation because normal site-packages is not writable")
Try running the installation using admin rights.

If this still doesn't work, copy the site-packages folder from the current installation path into the site-packages folder of blender. (Requires admin rights too)

This is a really annoying thing and only occurs in windows.

**Comment by m3dus444** [comment]
Thanks a lot for this answer, i will try to install with admin rights. You right I didn't notice that it changed folder's installation. Though, i added to path all path candidates for installation (worked with some frameworks).

Yeah, i can go on Linux i have dual boot, but i have to made the project i'm working on compatible with Windows (and Apple wich scares me a lot ngl) that's why. 

Anyway i'll keep you up to date thank for the info !

**Comment by m3dus444** [comment]
Alright, fixed the issue ✔️ 

You were quite right, i had to install with admin rights, but it worked only in powershell (python.exe && vtk commands) but in blender, it said it couldn't find the package. So i had to install from blender python interpreter as admin and then, add to path where the package got installed.

Thanks again ! ❤️
